### ISSUE TITLE
Provision error

### ISSUE THREAD

**Issue by tkdchen** [release-engineering/dist-git#17] opened 2018-01-21 04:16 UTC
I tried to up a vagrant machine simply by `vagrant up`, it fails at this step of provision.

```
==> distgit: Running provisioner: shell...
    distgit: Running: inline script
    distgit: Created symlink /etc/systemd/system/multi-user.target.wants/httpd.service → /usr/lib/systemd/system/httpd.service.
    distgit: Job for httpd.service failed because the control process exited with error code.
    distgit: See "systemctl  status httpd.service" and "journalctl  -xe" for details.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

These two SSL relative directives are not configured properly, 

```
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty
SSLCertificateKeyFile: file '/etc/pki/tls/private/localhost.key' does not exist or is empty
```

`httpd -t` reports syntax error in `/etc/httpd/conf.d/ssl.conf`.

**Comment by tkdchen** [comment] 2018-01-21 14:25
Provision works in `fedora/26-cloud-base`.

**Comment by clime** [comment] 2018-01-22 10:43
I could not reproduce the issue. I did `vagrant up` with the current Vagrantfile from master and it worked (distgit.vm.box was set to "fedora/27-cloud-base"). The Vagrantfile actually does not touch /etc/pki/tls/certs/localhost.crt or /etc/pki/tls/private/localhost.key and these files are referenced from /etc/httpd/conf.d/ssl.conf which is also not being modified. Could you please try just once more from a clean state to find out if this is reproducible? Thank you!

**Comment by tkdchen** [comment] 2018-01-28 01:52
I tried again from a clean state, clone the repo from github and `vagrant up`, and then this issue is reproducible. I'm using VirtualBox vagrant box `fedora/27-cloud-base (virtualbox, 20171105)`. Would it possible to be caused by the box?

**Comment by clime** [comment] 2018-01-31 20:21
> I tried again from a clean state, clone the repo from github and vagrant up, and then this issue is reproducible. I'm using VirtualBox vagrant box fedora/27-cloud-base (virtualbox, 20171105). Would it possible to be caused by the box?

Yes, base images (fedora/27-cloud-base (virtualbox, 20171105) vs. fedora/27-cloud-base (libvirt, 20171105)) seem different. One contains the localhost keys and the other doesn't.

httpd has a default VirtualHost configured in /etc/httpd/conf.d/ssl.conf that requires those keys. I guess providing own ssl.conf with just the basic SSL directives would be more error-prone.

**Comment by clime** [comment] 2018-02-03 13:07
Should be now fixed. Thanks for the report!

**Closed by clime** 2018-02-03 13:07 UTC
